[[redirects]]
  from = "/amor.html"
  to = "/amor"
  status = 301
  force = true

[[redirects]]
  from = "/amor"
  to = "/amor.html"
  status = 200 

[[redirects]]
  from = "/servicios/servicio-pintura.html"
  to = "/servicios/servicio-pintura"
  status = 301
  force = true

[[redirects]]
  from = "/servicios/servicio-pintura"
  to = "/servicios/servicio-pintura.html"
  status = 200
