[[redirects]]
  from = "/amor.html"
  to = "/amor"
  status = 301
  force = true

[[redirects]]
  from = "/amor"
  to = "/amor.html"
  status = 200 

  [[redirects]]
  from = "/servicios/*"
  to = "/servicios/:splat.html"
  status = 200

