[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# Usar query para detectar .html
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  force = true
  conditions = {Query = {path = "*.html"}}

[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404