[build]
  publish = "."

[redirects]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/amor.html"
  to = "/amor/"
  status = 301

[[redirects]]
  from = "/amor/"
  to = "/amor.html"
  status = 200
  force = true

# Redirección para 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  command = ""
  [context.production.environment]
    FORCE = "true"

[settings]
  trailing_slash = "always"
