#paginas Normales
[[redirects]]
  from = "/amor.html"
  to = "/amor"
  status = 301
  force = true
#categoria de servicios
[[redirects]]
  from = "/servicios/servicio-pintura.html"
  to = "/servicios/servicio-pintura"
  status = 301
  force = true
[[redirects]]
  from = "/servicios/ventana.html"
  to = "/servicios/ventana"
  status = 301
  force = true